### ISSUE TITLE
Duckduckgo.com always being visited instead of my site.

### ISSUE THREAD

**Issue by mherbold** [SafeExamBrowser/Chrominimum#1] opened 2020-05-19 13:38 UTC
1. Downloaded and installed Chrominium
2. Opened up the SEB config tool
3. Went to the Applications tab, and added c:\program files\chrominium\chrominium.exe
4. Added one argument for example https://www.google.com
5. Ticked the "Autostart" checkbox
6. Saved the config file.

When I run SEB it does fire up chrominium but the website it loads is duckduckgo.com... ?

See the screenshot below.  I have the command line argument set to https://www.google.com - but when I run SEB it fires up Chrominum and goes to duckduckgo.com instead.

![temp](https://user-images.githubusercontent.com/521887/82333085-1afd2600-999b-11ea-90bc-9484a97ee4b4.png)

**Comment by dbuechel** [comment] 2020-05-27 14:22
Sorry, I just saw your issue. I either did not get a notification from GitHub or I accidentally deleted it somehow.

I am still not able to reproduce your behavior. Could you share your SEB configuration?

**Comment by dbuechel** [comment] 2020-05-27 14:29
Turns out I wasn't watching my own repository. Sorry...

**Comment by mherbold** [comment] 2020-05-27 16:12
Here you go.

[SebClientSettings.zip](https://github.com/SafeExamBrowser/Chrominimum/files/4690062/SebClientSettings.zip)

**Comment by mherbold** [comment] 2020-05-27 16:16
Also a video showing what I am seeing...

https://youtu.be/OZKuwpyAs-I

**Comment by mherbold** [comment] 2020-05-27 16:18
To clarify - in the video, the google web page in the main window is coming from the Start URL in the general tab in the configuration settings.  In the application tab for chrominium.exe I have the arguments set to "https://www.google.com" but it is going to duckduckgo.com instead as you can see in the Chrominum child window in the video.

**Comment by dbuechel** [comment] 2020-05-27 16:59
I can't reproduce your problem, also not with your settings. Could you try to start Chrominimum outside of SEB, via command-line:

`C:\Program Files\Chrominimum\Chrominimum.exe https://www.google.com`

**Comment by mherbold** [comment] 2020-05-27 17:04
That does work - it loads up https://www.google.com if I run it from the
command line.  Could I somehow have an older version of SEB 3.0 that is
broken in this respect?

-- Marvin

**Comment by dbuechel** [comment] 2020-05-27 18:23
I don't think so. But you can try to download the latest build (3.0.0.151) from the build server: https://sebdev-let.ethz.ch/project/appveyor/seb-win-refactoring/build/job/ch1ljph2evkbw4tm/artifacts

Are you sure you're actually using the configuration you're editing? Or do you have another configuration in `%ProgramData%\SafeExamBrowser` where the argument is missing? You can find the configuration which is used in the runtime log.

**Comment by dbuechel** [comment] 2020-05-27 18:25
Wait, you're right: If you have a build lower than 3.0.0.130, then it won't work! I'm terribly sorry, I implemented everything but forgot to actually use the parameters before that:

https://github.com/SafeExamBrowser/seb-win-refactoring/commit/631fb583d753caeac27a5aade469115f92e06bc1

**Comment by mherbold** [comment] 2020-05-27 19:29
Yay!  Glad we were able to figure this out.  I was starting to think one of
us was going insane.  :-)

I wonder how hard it is to make a branch of the Chrominum code and to
implement a config option to make it not initialize the keyboard hook for
WebRTC.  I might take a stab at that.

-- Marvin

**Comment by dbuechel** [comment] 2020-05-27 19:58
Excellent! I'll close this then for now.

**Closed as completed by dbuechel** 2020-05-27 19:58 UTC
